### ISSUE TITLE
Insert Content to Header

### ISSUE THREAD

**Issue by merilturock** [beautylix/contentinsert#1]
Hello there,
          Thanks for the lovely plugin at first the plugin is working beautifully without any issues i just want small modification to be done & i need your help for that. The Ad inserted in Header is n ow showing above the menu but it will be grate if it shows below the heading of a page say "All Site Activity", "All site bookmarks" so i want to know how to change this can u plz help me on this.

**Comment by beautylix** [comment]
The simplest way is to edit the start.php

Open your start.php file

Find:

`elgg_extend_view('page/elements/header','contentinsert/topbanner');`

Change to:

`elgg_extend_view('page/elements/body', 'contentinsert/topbanner', '1');`

This should work.
